name: Despliegue FTP a InfinityFree

on:
  push:
    branches:
      - main # Se ejecuta cada vez que guardes cambios en la rama main

jobs:
  web-deploy:
    name: Desplegar código en InfinityFree
    runs-on: ubuntu-latest
    steps:
    - name: Obtener el código más reciente
      uses: actions/checkout@v4 # Actualizado a la versión 4

    - name: Sincronizar archivos por FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /htdocs/ # Carpeta pública de InfinityFree